### PR TITLE
Added Twitter user gender prediction

### PR DESCRIPTION
**Pull request by manjalshah**
## Related Issue

Closes: #14

### Describe the changes you've made

Used NLP and Logistic Regression to train the model which can predict gender of Twitter users from their text data.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots(optional)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

### CODE REVIEW

**Comment by manjalshah** [comment]
> Hey @manjalshah ! Plagiarism found . Its identical to https://www.kaggle.com/ofsenyayla/basic-nlp-implementation

Yes, I have taken implementation idea from some codes on kaggle but I have not completely copied from that. I have trained my model on text data and they have trained their model on description data of user.

**Comment by KilariBinduYadav** [comment]
> > Hey @manjalshah ! Plagiarism found . Its identical to https://www.kaggle.com/ofsenyayla/basic-nlp-implementation
> 
> Yes, I have taken implementation idea from some codes on kaggle but I have not completely copied from that. I have trained my model on text data and they have trained their model on description data of user.

Okay .

**Comment by Mrdecent08** [comment]
@manjalshah We can merge the PR but we cannot give the accepted label.

**Comment by himabindu-run** [comment]
> > > > @manjalshah We can merge the PR but we cannot give the accepted label.
> > > 
> > > 
> > > Please give that accepted label. I have tried to train my model on different details of user using so many different algorithms and come up with this highest accuracy by doing so much hard work.
> > 
> > 
> > Hey @manjalshah ! We cannot give the accepted label since it is almost identical to the link. Try implementing a different approach then we can consider your contribution and give the accepted label.
> 
> I have already tried different approach but it was not that efficient so would it be fine ? I have to use that nltk packages to process text kind of data in dataset so would that be fine if I use them with my different approach ?

Hey, @manjalshah Good day!
Yes, if you implemented some other approach without any plagiarism, we would love to take a look! Make another Issue and PR for that implementation!
For now, we will *not* accept this! We encourage innovation and diverse PRs.

**Pull request merged**
