### PR TITLE
Added car price prediction 

### PR DESCRIPTION
**Pull request by manjalshah**
## Related Issue

Closes: #8

### Describe the changes you've made

Created car price prediction model using random forest.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Screenshots(optional)

 Original           | Updated
 :--------------------: |:--------------------:
 original screenshot | updated screenshot |

### CODE REVIEW

**Comment by Mrdecent08** [comment]
Please add the issue number you are going to close.

**Comment by manjalshah** [comment]
> Please add the issue number you are going to close.

Added

**Review by Mrdecent08 — APPROVED** [review]
LGTM ! Thanks for your Contribution 🚀

**Review by KilariBinduYadav — DISMISSED** [review]

**Review by deephunt3r — CHANGES_REQUESTED** [review]
Could you please add your files in 
- Projects folder
   - Prediction folder(create one)
       - your files

**Comment by deephunt3r** [comment]
@manjalshah Hey! you just add submodule(mentioned the files). please add the files

**Comment by manjalshah** [comment]
> @manjalshah Hey! you just add submodule(mentioned the files). please add the files

Yes, I am trying to do that. Sorry, I am new to open source and not so familiar with git and github.

**Comment by deephunt3r** [comment]
> > @manjalshah Hey! you just add submodule(mentioned the files). please add the files
> 
> Yes, I am trying to do that. Sorry, I am new to open source and not so familiar with git and github.

no problem!! add files

**Comment by manjalshah** [comment]
> > > @manjalshah Hey! you just add submodule(mentioned the files). please add the files
> > 
> > 
> > Yes, I am trying to do that. Sorry, I am new to open source and not so familiar with git and github.
> 
> no problem!! add files Hey! you added the files correctly but delete the submodule prediction

I have changed name of that submodule to Car-Price-Prediction.

**Comment by deephunt3r** [comment]
> I have changed name of that submodule to Car-Price-Prediction.

could you please delete that!

**Comment by manjalshah** [comment]
> > I have changed name of that submodule to Car-Price-Prediction.
> 
> could you please delete that!

ok. After that, what should I do?

**Comment by deephunt3r** [comment]
> > > I have changed name of that submodule to Car-Price-Prediction.
> > 
> > 
> > could you please delete that!
> 
> ok. After that, what should I do?

https://gist.github.com/kyleturner/1563153 you can refer this and delete that submodule and let me know so I can merge your pr or you can create new pr

**Comment by manjalshah** [comment]
> > > > I have changed name of that submodule to Car-Price-Prediction.
> > > 
> > > 
> > > could you please delete that!
> > 
> > 
> > ok. After that, what should I do?
> 
> https://gist.github.com/kyleturner/1563153 you can refer this and delete that submodule and let me know so I can merge your pr or you can create new pr

Can you please check it now?

**Review by deephunt3r — APPROVED** [review]

**Comment by manjalshah** [comment]
Thank you so much. It was my first PR which get approved.

**Pull request merged**
