### PR TITLE
Added Wine quality prediction

### PR DESCRIPTION
**Pull request by 29riyasaxena**
## Related Issue

Closes: #3 

### Describe the changes you've made

I have added the jupyter notebook along with the dataset for wine quality prediction. I have used various regression algorithms in it.

### CODE REVIEW

**Comment by deephunt3r** [comment]
@29riyasaxena Hey, you just added Health Insurance files too! 
could please delete it?

**Comment by 29riyasaxena** [comment]
@deephunt3r Actually, I made 2 PR yesterday, one for wine quality prediction and the other for health insurance cost prediction. Do i have to still delete the health insurance files? (P.S. : I am a beginner at open-source)

**Comment by deephunt3r** [comment]
> @deephunt3r Actually, I made 2 PR yesterday, one for wine quality prediction and the other for health insurance cost prediction. Do i have to still delete the health insurance files? (P.S. : I am a beginner at open-source)

Okay! Don't worry I'll make the required changes at my side
learn about using branches!!

**Comment by 29riyasaxena** [comment]
Okay, Sure, I will learn about branches! Thank You!

**Review by Mrdecent08 — APPROVED** [review]
LGTM

**Review by KilariBinduYadav — APPROVED** [review]

**Review by deephunt3r — APPROVED** [review]

**Pull request merged**
